services: 

  gluetun-vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /lib/modules:/lib/modules:ro
    env_file:
      - ./torrent-stack.env
    ports:     
      - "8191:8191" # flaresolverr
      - "6881:6881" # qbittorrent
      - "6881:6881/udp" # qbittorrent
      - "8080:8080" # qbittorrent
      - "7878:7878" # radarr
      - "8989:8989" # sonarr
      - "8686:8686" # lidarr
      - "9117:9117" # jackett
      - "5055:5055" # jellyseerr

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - WEBUI_PORT=8080
    volumes:
      - /hdd/media/downloads:/downloads
      - /torrent/config/qbittorrent:/config 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.torrent.homelan`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.services.qbittorrent.loadbalancer.server.url=http://127.0.0.1:8080"

  radarr:
    image: ghcr.io/linuxserver/radarr
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /torrent/config/radarr:/config
      - /hdd/media/movies:/movies
      - /hdd/media/downloads:/downloads 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.torrent.homelan`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.url=http://127.0.0.1:7878"

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /torrent/config/sonarr:/config
      - /hdd/media/tv:/tv
      - /hdd/media/downloads:/downloads 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.torrent.homelan`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.services.sonarr.loadbalancer.server.url=http://127.0.0.1:8989"

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /torrent/config/lidarr:/config
      - /hdd/music/data:/music
      - /hdd/media/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.torrent.homelan`)"
      - "traefik.http.routers.lidarr.entrypoints=web"
      - "traefik.http.services.lidarr.loadbalancer.server.url=http://127.0.0.1:8686"

  jackett:
    image: ghcr.io/linuxserver/jackett
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /torrent/config/jackett:/config
      - /hdd/media/downloads:/downloads 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.torrent.homelan`)"
      - "traefik.http.routers.jackett.entrypoints=web"
      - "traefik.http.services.jackett.loadbalancer.server.url=http://127.0.0.1:9117"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    network_mode: "service:gluetun-vpn"
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Oslo
      - PORT=5055
    volumes:
      - /torrent/config/jellyseerr:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.torrent.homelan`)"
      - "traefik.http.routers.jellyseerr.entrypoints=web"
      - "traefik.http.services.jellyseerr.loadbalancer.server.url=http://127.0.0.1:5055"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    network_mode: "service:gluetun-vpn" 
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Oslo
      - HOST=0.0.0.0
      - PORT=8191
      - HEADLESS=true
      - BROWSER_TIMEOUT=55000

  traefik:
    image: docker.io/library/traefik:v3.7
    network_mode: "host"
    restart: unless-stopped
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8081
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.allowEmptyServices=true
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.torrent.homelan`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.services.dashboard.loadbalancer.server.url=http://127.0.0.1:8081"
